name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install
      - name: Run Tests & generate coverage
        run: |
          npm run coverage
      - name: Send coverage to Coveralls (parallel)
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          flag-name: run-$
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
          carryforward: "run-20.x,run-22.x,run-24.x"
